apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.1
          env:
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
          ports:
            - containerPort: 8086
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb
          livenessProbe:
            httpGet:
              path: /ping
              port: 8086
            initialDelaySeconds: 40
            timeoutSeconds: 4
      volumes:
        - name: "influxdb"
          persistentVolumeClaim:
            claimName: influxdb
